[package]
name = "ext2"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]

[features]
image_processing = ["image"]

[dependencies]
byteorder = "1.2.6"
uuid = "0.7.1"
image = { version = "*", optional = true }

[[example]]
name = "image"

required-features = ["image_processing"]
